= ngx-oauth
Jakub Jirutka <https://github.com/jirutka[@jirutka]>
:source-language: sh
:gh-name: jirutka/ngx-oauth
:gh-branch: master
:gh-url: https://github.com
:rocks-url: https://luarocks.org/modules
:rfc6749: http://tools.ietf.org/html/rfc6749
:rfc6265: http://tools.ietf.org/html/rfc6265
:ngx-http-core-doc: http://nginx.org/en/docs/http/ngx_http_core_module.html

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch={gh-branch}["Build Status", link="https://travis-ci.org/{gh-name}"]
image:https://coveralls.io/repos/{gh-name}/badge.svg?branch={gh-branch}&service=github["Coverage Status", link="https://coveralls.io/github/{gh-name}?branch={gh-branch}"]
endif::env-github[]

TBD


== Requirements

* http://nginx.org[nginx] with compiled https://github.com/openresty/lua-nginx-module[Lua module]
* http://luajit.org[LuaJIT] 2.0+, or http://www.lua.org[Lua] 5.1 (newer versions are not supported by lua-nginx yet)
* lua-resty-http [{gh-url}/pintsized/lua-resty-http[source]] [{rocks-url}/pintsized/lua-resty-http[LuaRocks]]
* lua-cjson [{gh-url}/mpx/lua-cjson[source]] [{rocks-url}/luarocks/lua-cjson[LuaRocks]], or luajson [{gh-url}/harningt/luajson[source]] [{rocks-url}/harningt/luajson[LuaRocks]]
* luaossl [{gh-url}/wahern/luaossl[source]] [{rocks-url}/daurnimator/luaossl[LuaRocks]]


== Usage

[source, nginx]
.Example of nginx.conf:
-------------------------------------------------------------------------------
http {

    # DNS servers used to resolve names of upstream servers into addresses.
    resolver 208.67.222.222 208.67.220.220 [2620:0:ccc::2] [2620:0:ccd::2];

    # Path of the file with trusted CA certificates.
    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

    # The verification depth in the server certificates chain.
    lua_ssl_verify_depth 3;

    # The Lua module search path.
    lua_package_path '/path/to/ngx-oauth/?.lua;;';

    ...

    server {
        listen 443 ssl;
        server_name client.example.org;

        ...

        set $oauth_client_id '01234567-89ab-cdef-0123-456789abcdef';
        set $oauth_client_secret 'very-top-secret-password';
        set $oauth_redirect_uri '/_oauth/callback';
        set $oauth_oaas_uri 'https://oaas.example.org/oauth';

        location /_oauth/login {
            content_by_lua_file '/path/to/ngx-oauth-login.lua';
        }

        location /_oauth/callback {
            content_by_lua_file '/path/to/ngx-oauth-redirect-handler.lua';
        }

        location /_oauth/logout {
            content_by_lua_file '/path/to/ngx-oauth-logout.lua';
        }

        location /_proxy {
            access_by_lua_file '/path/to/ngx-oauth-proxy.lua';

            rewrite ^/_proxy/(.*)$ /$1 break;
            proxy_pass https://resource-provider;
        }

        location / {
            ...
        }
    }
}
-------------------------------------------------------------------------------


== Configuration variables

$oauth_aes_bits::
  Selects the AES key length (in bits) for encrypting a refresh token stored in a cookie.
  The supported values are: `128`, `192`, and `256`.
  The default value is `128`.

$oauth_authorization_url::
  URL of the {rfc6749}#section-3.1[authorization endpoint] provided by the authorization server.
  This variable is required if `$oauth_oaas_uri` is not set; otherwise it defaults to `${oauth_oaas_uri}/authorize`.

$oauth_client_id::
  The {rfc6749}#section-2.2[client identifier] registered on the authorization server.
  This variable is *required.*

$oauth_client_secret::
  The {rfc6749}#section-2.3.1[client secret] (password).
  First _n_-bytes of this value, where _n_ equals `$oauth_aes_bits / 8`, is also used as a key for encrypting a refresh token stored in a cookie.
  This _n_ also defines the lower limit of the secret length.
  However, even if you use the default key length 128 bits, the client secret should be much longer (e.g. 32 characters).
  This variable is *required.*

$oauth_cookie_path::
  Specifies the {rfc6265}#section-4.1.2.4[Path attribute] for the cookies.
  The default value is `/`.

$oauth_cookie_prefix::
  The string to be used as a prefix for `access_token`, `refresh_token` and `username` cookies.
  The default value is `oauth_`.

$oauth_max_age::
  Specifies the {rfc6749}#section-4.1.2.2[Max-Age attribute] for the refresh_token cookie and the username cookie, in seconds.
  The Max-Age of the access_token cookie is determined as a minimum of this value and token’s `expires_in` attribute.
  The default value is `2592000` (30 days).

$oauth_oaas_uri::
  Base URI of the OAuth 2.0 authorization server.
  This variable is *required*, unless you set `$oauth_authorization_url`, `$oauth_token_url` and `$oauth_userinfo_url`.

$oauth_redirect_uri::
  URL of the _client’s_ {rfc6749}#section-3.1.2[redirection endpoint] previously registered on the authorization server.
  It may be full (absolute) URL, or just a path (starting with `/`) relative to {ngx-http-core-doc}#var_scheme[`$scheme`]`://`{ngx-http-core-doc}#var_server_name[`$server_name`].
  The default value is `/_oauth/callback`.

$oauth_scope::
  A space delimited set of OAuth scopes that should be requested.
  The default value is empty, i.e. all scopes allowed for the client will be requested.

$oauth_success_uri::
  Absolute or relative URI to which a browser should be redirected after successful authorization.
  The default value is `/`.

$oauth_token_url::
  URL of the {rfc6749}#section-3.2[token endpoint] provided by the authorization server.
  This variable is required if `$oauth_oaas_uri` is not set; otherwise it defaults to `${oauth_oaas_uri}/token`.

$oauth_userinfo_url::
  URL of the userinfo endpoint.
  This may be any GET resource secured by OAuth 2.0 that returns JSON with username (in the attribute `username`) of the user that has authorized the access token.
  This variable is required if `$oauth_oaas_uri` is not set; otherwise it defaults to `${oauth_oaas_uri}/userinfo`.


== Setup development environment

. Clone this repository:

    git clone https://github.com/jirutka/ngx-oauth.git
    cd ngx-oauth

. Source file `.envrc` into your shell (or manually add `$(pwd)/.env/bin` to your `PATH`):

    source .envrc

. Install LuaJIT and modules for development into directory `.env`:

    ./script/bootstrap
+
or to install nginx and Python modules for running integration tests as well, use:

    ./script/bootstrap-full

. Run tests with code coverage and linter:

    ./script/test
+
and integration tests:

    ./script/test-integration


These scripts should work on every up-to-date Unix system (tested on OS X, Gentoo, Slackware, and Ubuntu).


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
