#!/bin/bash
set -e

# Go to the project's root directory.
cd "$(dirname "$0")/.."

script/bootstrap

echo -e '\n==> Running tests...'
busted --shuffle --verbose

echo -e '\n==> Running linter...'
luacheck src/*
