#!/bin/bash
# vim: set ts=4:
#
# Runs unit tests and linter.
#
set -e

#======================  Functions  ======================#

report-coverage() {
	echo -e '\nHits\tMiss\tRate\tFile'
	echo -e '--------------------------------------------------'
	cat "$TEMP_DIR/luacov.report.out" | sed -nE '/^Summary/,$p' | tail -n+4
}


#========================  Main  =========================#

# Go to the project's root directory.
cd "$(dirname "$0")/.."

source script/common.sh
setup-path
script/bootstrap

einfo '==> Running unit tests...'
busted --shuffle --verbose --coverage
report-coverage

einfo '==> Running linter...'
luacheck src/*
