#!/bin/bash
# vim: set ts=4:
#
# Runs integration tests.
#
set -e -o pipefail

# Go to the project's root directory.
cd "$(dirname "$0")/.."

source script/common.sh
setup-path
script/bootstrap-full

einfo '==> Running integration tests...'
export TEMP_DIR
cd integration
py.test -v
